### ISSUE TITLE
title/subtitle should be combined for BibTeX "title" field

### ISSUE THREAD

**Issue by jowens** [front-matter/commonmeta-py#41]
Forked from https://github.com/front-matter/commonmeta-py/issues/27

I believe that this package populates the BibTeX `title` field directly from the input `title` field. However, if the input `subtitle` field is present, then the BibTeX `title` field should instead join the input `title` and `subtitle` fields with a colon.

Example: https://doi.org/10.1145/3448016.3452841 ("Vector Quotient Filters: Overcoming the Time/Space Trade-Off in Filter Design")

**Comment by mfenner** [comment]
Agree, I have done this in `commonmeta-py 0.7.0`, released today.
