### ISSUE TITLE
can we do -- for page ranges?

### ISSUE THREAD

**Issue by jowens** [front-matter/commonmeta-py#44]
https://github.com/front-matter/commonmeta-py/issues/40#issuecomment-1456535890

It appears here that your generated BibTeX uses an en-dash for page ranges. I believe it's slightly preferable to use ASCII for everything; not all tools do the right thing (sadly) with non-ASCII. Could you do `--` instead?

**Comment by mfenner** [comment]
Good suggestion. I saw this as an option in the underlying `bibtexparser` but wasn't sure what the general consensus is. Changed now.

**Comment by mfenner** [comment]
Closing this issue.
