### ISSUE TITLE
bibtex citekey ought to be just the DOI not the URL

### ISSUE THREAD

**Issue by jowens** [front-matter/commonmeta-py#45]
BibTeX citekeys are currently something like

`@inproceedings{https://doi.org/x.y/z.w,`

I don't think there's any value to the `https://doi.org/` and suggest that should be removed. Shorter is better when having to cite things.

(There's obviously a zillion different citekey styles, and you should just sidestep those; using the DOI is sensible and easy and unique.)

**Comment by mfenner** [comment]
Using the DOI is helpful in that it is a predictable and unique key. There is no need in using the DOI expressed as URL but I think also no harm. I think this comes from an earlier workflow where I was using Pandoc and bibtex to generate references where a URL has advantages.

**Comment by jowens** [comment]
I agree it's predictable and unique. I just wouldn't want to type it with all the prefixes! It's too long. Just the DOI part is equally predictable and unique. It would also take up a bunch of space in LaTeX source, which is IMHO undesirable as well.

**Comment by mfenner** [comment]
That makes sense. Two other considerations are citekeys for entries without a DOI, e.g. a NY Times article or software in GitHub. And I am also willing to implement shorter citekeys, e.g. bibtex alpha ("owe19" etc.) if that helps.

**Comment by jowens** [comment]
So *I* will personally rewrite every citekey whenever I import a bib entry (Emacs bibtex mode has auto support for this) for consistency. I'm just suggesting what I feel would be a good policy for a DOI-centered tool like yours. :) I don't know that you want to wade into different citekey formats; that's perhaps better handled downstream.
