### ISSUE TITLE
GitHub landing page still ink to Talbot docs

### ISSUE THREAD

**Issue by sdruskat** [front-matter/commonmeta-py#64]
Hi @mfenner 👋, very interesting project!

Just a quick heads up that the GitHub landing page still links to the `talbot` docs:

![grafik](https://user-images.githubusercontent.com/3007126/232997554-e6d42afe-6b79-4d75-a471-f24d4f1adcf5.png)

**Comment by mfenner** [comment]
Thanks. This has been fixed, now correctly pointing to https://commonmeta-py.docs.front-matter.io/
